name: dstat 
version: 0.7.3
summary: Versatile resource statistic tool 
description: This is my-snap's description  # a longer description for the snap
confinement: devmode  # use "strict" to enforce system access only via declared interfaces

apps:
  dstat:
    command: dstat
    plugs: [home, system-observe]
parts:
  dstat:
    plugin: make 
    source: https://github.com/dagwieers/dstat/archive/0.7.3.tar.gz 
    build-packages: [gcc, libc6-dev]
